name: Auto-Tag Release

on:
  push:
    branches:
      - "**"
      # - master

jobs:
  release_new_tag:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v2
        with:
          token: ${{secrets.github_token}}
      - name: Read VERSION file
        id: getversion
        uses: ./.github/actions/cat-file
        with:
          file: VERSION
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: v${{ steps.getversion.outputs.text }}.${{ steps.buildnumber.outputs.build_number }}
          prerelease: false
