name: Terraform CI/CD

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - docs/**.md
      - "*.md"

jobs:
  terraform_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Clone git repo
        uses: actions/checkout@v1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.0
      - name: Terraform Linter Check (Formatting)
        run: |
          terraform fmt -recursive -check
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.14" # The Go version to download (if necessary) and use.
      - name: "Terraform Code Standards Check"
        run: |
          GO111MODULE="on" go get github.com/segmentio/terraform-docs
          export PATH=$HOME/go/bin:$PATH
          pip3 install --pre slalom.dataops
          s-infra check_tf_metadata ./catalog \
              --check_module_headers \
              --required_input_vars=[name_prefix,resource_tags,environment] \
              --required_output_vars=[summary] \
              --check_input_descriptions \
              --check_output_descriptions \
              --raise_error
          s-infra check_tf_metadata ./components \
              --check_module_headers \
              --required_input_vars=[name_prefix,resource_tags,environment] \
              --required_output_vars=[] \
              --check_input_descriptions \
              --check_output_descriptions \
              --raise_error

  tf_test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        # python-version: [3.7]
        sample-id:
          - airflow-on-aws
          - dbt-and-singer-on-aws
          - kitchen-sink-on-aws
          - ml-ops-on-aws
          - mysql-on-aws
          - postgres-on-aws
          - redshift-on-aws
          - s3-lambda-trigger
          - secrets-manager-on-aws
          - sftp-on-aws
          - tableau-on-aws
    steps:
      - name: Clone git repo
        uses: actions/checkout@v1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.0
      - name: "Terraform Init (Sample #${{ matrix.sample-id }})"
        run: |
          cd ./samples/${{ matrix.sample-id }}
          terraform init
      - name: "Terraform Validate (Sample #${{ matrix.sample-id }})"
        run: |
          cd ./samples/${{ matrix.sample-id }}
          terraform validate
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: "Terraform Plan and Test (Sample #${{ matrix.sample-id }})"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # TODO: Revert to pip install `terraform-compliance` after:
        # https://github.com/eerkunt/terraform-compliance/pull/351
        run: |
          cp .secrets/aws-credentials.template .secrets/aws-credentials
          pip install git+https://github.com/Kudbettin/terraform-compliance@terraform0.13
          cd ./samples/${{ matrix.sample-id }}
          terraform plan -out plan.out
          terraform show -json plan.out > plan.out.json
          echo "Num Lines:"
          wc -l plan.out.json
          echo "-------"
          head -1 plan.out.json
          echo "-------"
          tail -1 plan.out.json > plan.out-2.json
          echo "-------"
          terraform-compliance -p plan.out-2.json -f ../../tests/rules
